services:
  db: 
    image: mongo
    env_file:
      - .env
    ports:
      - $MONGO_PORT:$MONGO_PORT
    volumes:
      - ./data/db:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  ai-queue:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
  ai-queue-server:
    image: node:18-alpine
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    env_file:
      - .env
    links:
      - ai-queue
    depends_on:
      - ai-queue
    environment:
      - REDIS_URL=redis://ai-queue:6379
    command: npm run start:ai-queue
volumes:
  cache:
    driver: local