services:
  db: 
    image: mongo
    env_file:
      - .env
    ports:
      - $MONGO_PORT:$MONGO_PORT
    volumes:
      - ./data/db:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  ai-queue:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./data/redis:/data
  ai-queue-server:
    build: 
      context: "."
      dockerfile: ai-queue/Dockerfile
    env_file:
      - .env
    ports:
      - 8080:80
    links:
      - ai-queue
    depends_on:
      - ai-queue
    environment:
      - REDIS_URL=redis://ai-queue:6379
      - AI_QUEUE_LOG=1
    command: npm run start:ai-queue