services:
  db: 
    image: mongo
    env_file:
      - .env
    ports:
      - $MONGO_PORT:$MONGO_PORT
    volumes:
      - ./data/db:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  ai-queue:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./data/redis:/data
  ai-queue-server:
    build: 
      context: .
      dockerfile: packages/ai-queue/docker/Dockerfile
      target: dev
    volumes:
      - ./packages/ai-queue:/home/node/app/packages/ai-queue
      - /home/node/app/packages/ai-queue/.ai-queue/
      - /home/node/app/packages/app/node_modules/
      - /home/node/app/packages/ai-queue/node_modules/
    env_file:
      - packages/ai-queue/.env
    ports:
      - 8080:80
      - 9229:9229
    links:
      - ai-queue
    depends_on:
      - ai-queue
    environment:
      - REDIS_URL=redis://ai-queue:6379
  app-dev-server:
    build: 
      context:    .
      dockerfile: packages/app/docker/Dockerfile
      target:     dev
    volumes:
      - /home/node/app/packages/app/.next/
      - /home/node/app/node_modules/
      - /home/node/app/packages/app/node_modules/
      - /home/node/app/packages/ai-queue/node_modules/
      - ./:/home/node/app/
    env_file:
      - packages/app/.env
    ports:
      - 3000:3000
      - 9230:9230
      - 9231:9231
      - 9232:9232
      - 9233:9233
      - 9234:9234
    links:
      - ai-queue
      - db
    environment:
      - REDIS_URL=redis://ai-queue:6379
      - MONGO_HOST=db