services:
  db: 
    image: mongo
    env_file:
      - .env
    ports:
      - $MONGO_PORT:$MONGO_PORT
    volumes:
      - ./data/db:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  ai-queue:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./data/redis:/data
  ai-queue-server:
    build: 
      context: ai-queue
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./ai-queue:/home/node/app/
      - queue-server-deps:/home/node/app/node_modules/
      - queue-server-dist:/home/node/app/.ai-queue/
    env_file:
      - ai-queue/.env
    ports:
      - 8080:80
      - 9229:9229
    links:
      - ai-queue
    depends_on:
      - ai-queue
    environment:
      - REDIS_URL=redis://ai-queue:6379
  app-dev-server:
    build: 
      context: .
      dockerfile: app/docker/Dockerfile
      target: dev
    volumes:
      - ./:/home/node/app/
      - app-server-data:/home/node/app/data/
      - app-server-dist:/home/node/app/.next/
      - app-server-deps:/home/node/app/node_modules/
      - app-server-ai-deps:/home/node/app/ai-queue/node_modules/
      - app-server-ai-dist:/home/node/app/ai-queue/.ai-queue/
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9230:9230
      - 9231:9231
      - 9232:9232
      - 9233:9233
      - 9234:9234
    links:
      - ai-queue
      - db
    environment:
      - REDIS_URL=redis://ai-queue:6379
      - MONGO_HOST=db
volumes:
  queue-server-deps:
    driver: local
  queue-server-dist:
    driver: local
  app-server-deps:
    driver: local
  app-server-dist:
    driver: local
  app-server-data:
    driver: local
  app-server-ai-deps:
    driver: local
  app-server-ai-dist:
    driver: local